{
  "build": {
    "command": "npm run build",
    "publish": "build",
    "environment": {
      "REACT_APP_API_URL": "https://your-backend-url.railway.app"
    }
  },
  "redirects": [
    {
      "from": "/api/*",
      "to": "https://your-backend-url.railway.app/api/:splat",
      "status": 200
    }
  ]
}
